spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/letscrackitt
spring.datasource.username=postgres
spring.datasource.password=shraddha

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=letscrackitt_super_secret_key_make_it_long_256bits_minimum
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173

# Server
server.port=8080